### ISSUE TITLE
Installing `spruce` via Homebrew fails (404)

### ISSUE THREAD

**Issue by jahio** [cloudfoundry-community/aws-nat-bastion-bosh-cf#14]
According to https://github.com/starkandwayne/homebrew-cf, to install `spruce` via Homebrew you do the following:

```
brew tap starkandwayne/cf
brew install spruce
```

That, unfortunately, doesn't work; it tries to download a GitHub release of `spruce` version 1.2.**1**, when the most recently released version at [geofffranks/spruce](https://github.com/geofffranks/spruce) is 1.2.**0**.

Wasn't sure which repository to open an issue on with this, since the instructions say to tap `starkandwayne/cf` even though the repository location is `starkandwayne/homebrew-cf`, `spruce` itself is under [geofffranks/spruce](https://github.com/geofffranks/spruce), and `1.2..1` as a release doesn't exist but the brew tap location clearly references that version, [as this commit shows](https://github.com/starkandwayne/homebrew-cf/commit/98311afd57b6c1c7a934374746bb870bf72fef6d).

![](http://d.pr/i/1jNOi+)

@geofffranks - ping for your information as you'll likely have to decide how you want to handle this mixup.

**Comment by geofffranks** [comment]
This is an issue in the spruce CI pipeline, also reported in https://github.com/geofffranks/spruce/pull/117, will fix today via https://github.com/geofffranks/spruce/issues/116
